### ISSUE TITLE
Lagrangian post-processing should be renamed.

### ISSUE THREAD

**Issue by OGaboriault** [chaos-polymtl/lethe#1176]
In the parameter file, it is the only parameter starting with a capital letter. Also, the output file it is generating should be renamed since we have two post-processing tool now. (Force chains and this)

**Comment by acdaigneault** [comment]
Renaming the output files for the post processing may makes some post-processing code in examples not compatible. I do not see the issue since the force chain feature has its own output name.
I agree with the tiny annoying capital letter tho x)

**Comment by blaisb** [comment]
I'll take care of removing the capital letter which is super annoying. The rest I agree with @acdaigneault comments that it makes sense. It's just a bunch of lagrangian post-processing
