### ISSUE TITLE
VoF BDF2 + adaptive mesh refinement 

### ISSUE THREAD

**Issue by AmishgaAlphonius** [chaos-polymtl/lethe#1288]
A deal.ii version dependency when using adaptive mesh refinement on the phase fraction with the BDF velocity extrapolation in VOF has been noticed this needs to be investigated further (PR #1286). The number of refined and coarsened cells varies with the deal.ii version used.

**Comment by blaisb** [comment]
I don't necessarily think that's a bug though. I'm not sure if there was not any slight deal.II version changes in how the error estimator works or even a round-off error that could not lead to that change.
If you think about it, any small fluctuation in the results will fluctuate the error indicator value and this can easily propagate to the number of cells refined (other than if the change is like super dramatic)
