### ISSUE TITLE
Duplicated code for constraints in navier_stokes solver

### ISSUE THREAD

**Issue by blaisb** [chaos-polymtl/lethe#1303]
There is a lot of duplicated code in the way constraints are managed between the navier_stokes_matrix_based, navier_stokes_block_matrix and navier_stokes_matrix_free code.
All of the constraint management could be moved to the base class and the exception handling for the few boundary conditions that are not managed correctly could be moved elsewhere. This would remove a lot of line of codes and would have prevented bug like the one I fixed in #1302 .

@lpsaavedra do you want to do it or I can take care of it :). Your call

**Comment by lpsaavedra** [comment]
I can take care of it!
